CREATE TABLE IF NOT EXISTS BOOK
(
    ID         SERIAL PRIMARY KEY,
    TITLE      VARCHAR(255) NOT NULL,
    ISBN       VARCHAR(20)  NOT NULL UNIQUE,
    AUTHOR     VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS COLLECTION
(
    ID         SERIAL PRIMARY KEY,
    NAME       VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS BOOK_COLLECTION
(
    BOOK_ID       BIGINT REFERENCES book (id) ON DELETE CASCADE,
    COLLECTION_ID BIGINT REFERENCES collection (id) ON DELETE CASCADE,
    PRIMARY KEY (BOOK_ID, COLLECTION_ID)
    );
